### ISSUE TITLE
Merge Release Upstream Release v4.0.0

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#416]
[DMPRoadmap Release v4.0.0](https://github.com/DMPRoadmap/roadmap/releases/tag/v4.0.0)
[DMPRoadmap v3.x to v4.x Upgrade Guide](https://github.com/DMPRoadmap/roadmap/wiki/Upgrading-from-v3.x-to-v4.x)

TODO:
- [x] https://github.com/portagenetwork/roadmap/issues/414
- [x] Make sure all Rspec tests pass
- [x] Make sure all GitHub Actions tests are functioning

**Comment by aaronskiba** [comment]
`config/environments/production.rb`

```ruby
# frozen_string_literal: true

<<<<<<< HEAD
require 'syslog/logger'
=======
require 'active_support/core_ext/integer/time'
>>>>>>> release-v4.0.0

Rails.application.configure do
  # Verifies that versions and hashed value of the package contents in the project's
  # package.json
  config.webpacker.check_yarn_integrity = false

  # Settings specified here will take precedence over those in config/application.rb.

  # Verifies that versions and hashed value of the package contents in the project's
  # package.json
  # config.webpacker.check_yarn_integrity = false

  # Code is not reloaded between requests.
  config.cache_classes = true

  # Eager load code on boot. This eager loads most of Rails and
  # your application in memory, allowing both threaded web servers
  # and those relying on copy on write to perform better.
  # Rake tasks automatically ignore this option for performance.
  config.eager_load = true

  # Full error reports are disabled and caching is turned on.
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true

  # Enable Rack::Cache to put a simple HTTP cache in front of your application
  # Add `rack-cache` to your Gemfile before enabling this.
  # For large-scale production use, consider using a caching reverse proxy like
  # NGINX, varnish or squid.
  # config.action_dispatch.rack_cache = true

  # Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?

  # Specifies the header that your server uses for sending files.
  # config.action_dispatch.x_sendfile_header = 'X-Sendfile' # for Apache
  # config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect' # for NGINX

  # Force all access to the app over SSL, use Strict-Transport-Security, and use secure
  # cookies.
  # config.force_ssl = true

  # Use the lowest log level to ensure availability of diagnostic information
  # when problems arise.
  config.log_level = :warn

  # Prepend all log lines with the following tags.
  # config.log_tags = [ :subdomain, :uuid ]

  # Use a different logger for distributed setups.
  # config.logger = ActiveSupport::TaggedLogging.new(SyslogLogger.new)

  # Use a different cache store in production.
  # config.cache_store = :mem_cache_store

  # Enable serving of images, stylesheets, and JavaScripts from an asset server.
  # config.action_controller.asset_host = 'http://assets.example.com'

  # Ignore bad email addresses and do not raise email delivery errors.
  # Set this to true and configure the email server for immediate delivery to raise
  # delivery errors.
  # config.action_mailer.raise_delivery_errors = false

  # Set default host for mailer URLs
  # config.action_mailer.default_url_options = {host: "example.com"}

  # Enable locale fallbacks for I18n (makes lookups for any locale fall back to
  # the I18n.default_locale when a translation cannot be found).
  config.i18n.fallbacks = true

  # Send deprecation notices to registered listeners.
  config.active_support.deprecation = :notify

<<<<<<< HEAD
  # Include working directory name in log for servers running multiple Rails instances.
  # logger = ActiveSupport::Logger.new(STDOUT)
  # logger.formatter = ::Logger::Formatter.new
  # config.logger = ActiveSupport::TaggedLogging.new(logger)
  # config.log_tags = [ Rails.root.to_s.split('/').last ]
=======
  # Log disallowed deprecations.
  config.active_support.disallowed_deprecation = :log

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Use default logging formatter so that PID and timestamp are not suppressed.
  config.log_formatter = ::Logger::Formatter.new

  # Use a different logger for distributed setups.
  # require 'syslog/logger'
  # config.logger = ActiveSupport::TaggedLogging.new(Syslog::Logger.new 'app-name')

  if ENV['RAILS_LOG_TO_STDOUT'].present?
    logger           = ActiveSupport::Logger.new($stdout)
    logger.formatter = config.log_formatter
    config.logger    = ActiveSupport::TaggedLogging.new(logger)
  end
>>>>>>> release-v4.0.0

  # Do not dump schema after migrations.
  config.active_record.dump_schema_after_migration = false

<<<<<<< HEAD
  # Use syslog for logging
  config.logger = ActiveSupport::TaggedLogging.new(Syslog::Logger.new('dmp_assistant'))

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: Rails.application.secrets.smtp_address,
    port: Rails.application.secrets.smtp_port,
    domain: Rails.application.secrets.smtp_domain,
    user_name: Rails.application.secrets.smtp_user_name,
    password: Rails.application.secrets.smtp_password,
    authentication: Rails.application.secrets.smtp_authentication || 'plain',
    enable_starttls_auto: true
  }

  # Fix JSON Download Error
  Rails.application.routes.default_url_options[:host] = "assistant.portagenetwork.ca"
end
=======
  # Inserts middleware to perform automatic connection switching.
  # The `database_selector` hash is used to pass options to the DatabaseSelector
  # middleware. The `delay` is used to determine how long to wait after a write
  # to send a subsequent read to the primary.
  #
  # The `database_resolver` class is used by the middleware to determine which
  # database is appropriate to use based on the time delay.
  #
  # The `database_resolver_context` class is used by the middleware to set
  # timestamps for the last write to the primary. The resolver uses the context
  # class timestamps to determine how long to wait before reading from the
  # replica.
  #
  # By default Rails will store a last write timestamp in the session. The
  # DatabaseSelector middleware is designed as such you can define your own
  # strategy for connection switching and pass that into the middleware through
  # these configuration options.
  # config.active_record.database_selector = { delay: 2.seconds }
  # config.active_record.database_resolver = ActiveRecord::Middleware::DatabaseSelector::Resolver
  # config.active_record.database_resolver_context = ActiveRecord::Middleware::DatabaseSelector::Resolver::Session

  # Rails 6+ adds middleware to prevent DNS rebinding attacks:
  #    https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization
  #
  # This allows us to define the hostname and add it to the whitelist. If you attempt
  # to access the site and receive a 'Blocked host' error then you will need to
  # set this environment variable
  config.hosts << ENV['DMPROADMAP_HOST'] if ENV['DMPROADMAP_HOST'].present?
end
# Used by Rails' routes url_helpers (typically when including a link in an email)
Rails.application.routes.default_url_options[:host] = ENV.fetch('DMPROADMAP_HOST', 'example.org')
>>>>>>> release-v4.0.0

```

**Comment by aaronskiba** [comment]
`config/initializers/translation.rb`

```ruby
# frozen_string_literal: true

<<<<<<< HEAD
## TODO Verify functionality after merging
=======
# New with Rails 6+, we need to define the list of locales outside the context of
# the Database since thiss runs during startup. Trying to access the DB causes
# issues with autoloading; 'DEPRECATION WARNING: Initialization autoloaded the constants ... Language'
#
# Note that the entries here must have a corresponding directory in config/locale, a
# YAML file in config/locales and should also have an entry in the DB's languages table
SUPPORTED_LOCALES = %w[de en-CA en-GB en-US es fi fr-CA fr-FR pt-BR sv-FI tr-TR].freeze
# You can define a subset of the locales for your instance's version of Translation.io if applicable
CLIENT_LOCALES = %w[de en-CA en-GB en-US es fi fr-CA fr-FR pt-BR sv-FI tr-TR].freeze
DEFAULT_LOCALE = 'en-GB'
# Here we define the translation domains for the Roadmap application, `app` will
# contain translations from the open-source repository and ignore the contents
# of the `app/views/branded` directory.  The `client` domain will
#
# When running the application, the `app` domain should be specified in your environment.
# the `app` domain will be searched first, falling back to `client`
#
# When generating the translations, the rake:tasks will need to be run with each
# domain specified in order to generate both sets of translation keys.
if !ENV['DOMAIN'] || ENV['DOMAIN'] == 'app'
  TranslationIO.configure do |config|
    config.api_key              = ENV.fetch('TRANSLATION_API_ROADMAP', nil)
    config.source_locale        = 'en'
    config.target_locales       = SUPPORTED_LOCALES
    config.text_domain          = 'app'
    config.bound_text_domains   = %w[app client]
    config.ignored_source_paths = ['app/views/branded/', 'node_modules/']
    config.locales_path         = Rails.root.join('config', 'locale')
  end
elsif ENV['DOMAIN'] == 'client'
  TranslationIO.configure do |config|
    config.api_key              = ENV.fetch('TRANSLATION_API_CLIENT', nil)
    config.source_locale        = 'en'
    config.target_locales       = CLIENT_LOCALES
    config.text_domain          = 'client'
    config.bound_text_domains = ['client']
    config.ignored_source_paths = ignore_paths
    config.disable_yaml         = true
    config.locales_path         = Rails.root.join('config', 'locale')
  end
end
>>>>>>> release-v4.0.0

# # Control ignored source paths
# # Note, all prefixes of the directory you want to translate must be defined here
def ignore_paths
  Dir['**/'] - Dir['app/**/']
end

<<<<<<< HEAD
TranslationIO.configure do |config|
  config.api_key        = Rails.application.secrets.translation_io_api_key
  config.source_locale  = 'en'
  config.target_locales = %w[en-CA en-GB fr-CA]
  config.ignored_source_paths = ignore_paths
  config.disable_yaml         = true

  # Uncomment this if you don't want to use gettext
  # config.disable_gettext = true

  # Uncomment this if you already use gettext or fast_gettext
  config.locales_path = File.join('config', 'locale')
  config.db_fields = {
    'Theme' => %w[title description],
    'QuestionFormat' => %w[title description],
    'Template' => %w[title description],
    'Phase' => %w[title description],
    'Section' => %w[title description],
    'Question' => %w[text default_value],
    'Annotation' => ['text'],
    'ResearchDomain' => ['label']
  }
  # Find other useful usage information here:
  # https://github.com/translation/rails#readme
end

I18n.enforce_available_locales = false
I18n.default_locale = :'en-CA'

# frozen_string_literal: true

# # Here we define the translation domains for the Roadmap application, `app` will
# # contain translations from the open-source repository and ignore the contents
# # of the `app/views/branded` directory.  The `client` domain will
# #
# # When running the application, the `app` domain should be specified in your environment.
# # the `app` domain will be searched first, falling back to `client`
# #
# # When generating the translations, the rake:tasks will need to be run with each
# # domain specified in order to generate both sets of translation keys.
# if !ENV["DOMAIN"] || ENV["DOMAIN"] == "app"
#   TranslationIO.configure do |config|
#     config.api_key              = ENV["TRANSLATION_API_ROADMAP"]
#     config.source_locale        = "en"
#     config.target_locales       = %w[de en-GB en-US es fr-FR fi sv-FI pt-BR en-CA fr-CA]
#     config.text_domain          = "app"
#     config.bound_text_domains   = %w[app client]
#     config.ignored_source_paths = ["app/views/branded/"]
#     config.locales_path         = Rails.root.join("config", "locale")
#   end
# elsif ENV["DOMAIN"] == "client"
#   TranslationIO.configure do |config|
#     config.api_key              = ENV["TRANSLATION_API_CLIENT"]
#     config.source_locale        = "en"
#     config.target_locales       = %w[fi sv-FI]
#     config.text_domain          = "client"
#     config.bound_text_domains = ["client"]
#     config.ignored_source_paths = ignore_paths
#     config.disable_yaml         = true
#     config.locales_path         = Rails.root.join("config", "locale")
#   end
# end

# # Setup languages
#
# table = ActiveRecord::Base.connection.table_exists?("languages") rescue false
# # if table
#   def default_locale
#     Language.default.try(:abbreviation) || "en-GB"
#   end

#   def available_locales
#     Language.sorted_by_abbreviation.pluck(:abbreviation).presence || [default_locale]
#   end

#   I18n.available_locales = Language.all.pluck(:abbreviation)

#   I18n.default_locale = Language.default.try(:abbreviation) || "en-GB"
# else
#   def default_locale
#     Rails.application.config.i18n.available_locales.first || "en-GB"
#   end

#   def available_locales
#     Rails.application.config.i18n.available_locales = %w[en-GB en-US]
#   end

#   I18n.available_locales = ["en-GB"]

#   I18n.default_locale = "en-GB"
# end
=======
# Setup languages
def default_locale
  DEFAULT_LOCALE
end

def available_locales
  SUPPORTED_LOCALES.sort { |a, b| a <=> b }
end

I18n.available_locales = SUPPORTED_LOCALES

I18n.default_locale = DEFAULT_LOCALE
>>>>>>> release-v4.0.0

```
