### ISSUE TITLE
Deployment Checklist For Release `4.1.1+portage-4.2.0`

### ISSUE THREAD

**Issue by aaronskiba** [portagenetwork/roadmap#866]
This issue is meant to serve as a checklist to ensure that no steps are missed with the deployment of the upcoming `4.1.1+portage-4.1.4` release.

- [x] Add values for `cilogon_client_id` and `cilogon_secret_key` secrets (across all environments)
- [x] Update values for `omniauth_full_host` secret within Sandbox and Production enviroments
- [x] Perform `bundle exec rails upgrade:dmp_assistant_v4_2_0`
- [ ] Remove the `rake sessions:cleanup` cronjob that is currently running within Production, Staging, and Sandbox

**Comment by aaronskiba** [comment]
We did not use the rake task when we first tested staging, instead we performed the tasks manually like so:
- Executed the following command from rails console
  - ```ruby
    IdentifierScheme.create(name: 'openid_connect', description: "CILogon", active: true, context: 1, identifier_prefix: "http://cilogon.org/serverE/users/")
    ```
- Execute command to remove sessions table (`bundle exec rails db:migrate`)
